/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mister dude (https://sketchfab.com/misterdude)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/iphone-14-pro-5cb0778041a34f09b409a38c687bb1d4
title: Iphone 14 Pro
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Iphone(props) {
  const { nodes, materials } = useGLTF('/iphone.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={200.67}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/iphone.gltf')
